//часть компоуза, контейнер nginx полностью рабочее, но  не нужно


  pic_client:
    image: nginx:latest
    container_name: pic_client
    restart: always
    networks:
      - traefik
    volumes:
      - /data/pics/sys/nginx-data/:/data/static:ro
      - /data/pics/sys/nginx-log/:/var/log/nginx
    command:
      - /bin/sh
      - -c
      - |
        echo "server {
          listen 3381;
          server_name localhost;

          access_log /var/log/nginx/access.log;
          error_log /var/log/nginx/error.log;

          location / {
            root /data/static;
            index  index.html index.htm;
            etag on;
            if_modified_since before;
            expires 30d;
            add_header Cache-Control 'public, max-age=2592000';
          }
        }" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`${PIC_DOMAIN}`)
      - traefik.http.routers.nginx.service=nginx
      - traefik.http.routers.nginx.entryPoints=web

      - traefik.http.routers.nginxSecure.rule=Host(`${PIC_DOMAIN}`)
      - traefik.http.routers.nginxSecure.service=nginx
      - traefik.http.routers.nginxSecure.entryPoints=webSecure
      - traefik.http.routers.nginxSecure.tls.certResolver=letsEncrypt

      - traefik.http.middlewares.nginx-headers.headers.FrameDeny=true
      - traefik.http.middlewares.nginx-headers.headers.browserXssFilter=true
      - traefik.http.middlewares.nginx-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.nginx-headers.headers.stsSeconds=315360000
      - traefik.http.middlewares.nginx-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.nginx-headers.headers.stsPreload=true

      - traefik.http.middlewares.https-redirect.redirectScheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectScheme.permanent=true

      # - traefik.http.middlewares.compress.compress=true

      - traefik.http.routers.nginx.middlewares=nginx-headers@docker,https-redirect@docker
      - traefik.http.routers.nginxSecure.middlewares=nginx-headers@docker,https-redirect@docker

      - traefik.http.services.nginx.loadbalancer.server.port=3381