name: Deploy ifrastructure to DEV

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    environment:
      name: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      # - name: Test SSH Connection
      #   run: |
      #     echo "${{ secrets.DMZ_GIT_ACTIONS_PROD }}" > ssh_key
      #     chmod 600 ssh_key
      #     ssh -i ssh_key -o StrictHostKeyChecking=no root@domiz.org echo "SSH connection successful"

      - name: Copy files on server
        uses: appleboy/scp-action@master
        with:
          host: dmzdev.xyz
          port: 22
          username: root
          key: ${{ secrets.NMZ_GIT_ACTIONS }}
          source: docker,docker-compose-dev.yaml,.env.dev
          target: /srv
          overwrite: true
          debug: true

      - name: Docker compose up
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd /srv
            touch .htpasswd
            htpasswd -bB .htpasswd ${{ secrets.BASIC_AUTH_USER }} ${{ secrets.BASIC_AUTH_PASSWORD }}
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            export MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
            export MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
            export IMGPROXY_KEY=${{ secrets.IMGPROXY_KEY }}
            export IMGPROXY_SALT=${{ secrets.IMGPROXY_SALT }}
            docker compose -f docker-compose-dev.yaml --env-file .env.dev pull
            docker compose -f docker-compose-dev.yaml --env-file .env.dev down
            docker compose -f docker-compose-dev.yaml --env-file .env.dev up -d --remove-orphans
          host: dmzdev.xyz
          port: 22
          username: root
          key: ${{ secrets.NMZ_GIT_ACTIONS }}
