name: Deploy ifrastructure to DEV

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    environment:
      name: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Copy files on server
        uses: appleboy/scp-action@master
        with:
          host: organiq.ru
          port: 7722
          username: root
          key: ${{ secrets.NMZ_GIT_ACTIONS }}
          source: docker,docker-compose-dev.yaml
          target: /srv
          overwrite: true
          debug: true

      - name: Docker compose up
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd /srv
            touch .htpasswd
            htpasswd -bB .htpasswd ${{ vars.BASIC_AUTH_USER }} ${{ secrets.BASIC_AUTH_PASSWORD }}
            export TRAEFIK_DOMAIN=${{ vars.TRAEFIK_DOMAIN }}
            export METRICS_DOMAIN=${{ vars.METRICS_DOMAIN }}
            export WHOAMI_DOMAIN=${{ vars.WHOAMI_DOMAIN }}
            export NODE_DOMAIN=${{ vars.NODE_DOMAIN }}
            export PROMETHEUS_DOMAIN=${{ vars.PROMETHEUS_DOMAIN }}
            docker compose -f docker-compose-dev.yaml pull
            docker compose -f docker-compose-dev.yaml down
            docker compose -f docker-compose-dev.yaml up -d --remove-orphans
          host: organiq.ru
          port: 7722
          username: root
          key: ${{ secrets.NMZ_GIT_ACTIONS }}
