name: P2P ifrastructure to PROD
on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    environment:
      name: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      # - name: Test SSH Connection
      #   run: |
      #     echo "${{ secrets.DMZ_GIT_ACTIONS_PROD }}" > ssh_key
      #     chmod 600 ssh_key
      #     ssh -i ssh_key -o StrictHostKeyChecking=no root@domiz.org echo "SSH connection successful"

      - name: Copy files on server
        uses: appleboy/scp-action@master
        with:
          host: domiz.org
          port: 22
          username: root
          key: ${{ secrets.DMZ_GIT_ACTIONS_PROD }}
          source: docker,docker-compose-prod.yaml,.env.prod
          target: /srv
          overwrite: true
          debug: true

      - name: Docker compose up
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd /srv
            touch .htpasswd
            htpasswd -bB .htpasswd ${{ secrets.BASIC_AUTH_USER }} ${{ secrets.BASIC_AUTH_PASSWORD }}
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            export MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
            export MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
            docker compose -f docker-compose-prod.yaml --env-file .env.prod pull
            docker compose -f docker-compose-prod.yaml --env-file .env.prod down
            docker compose -f docker-compose-prod.yaml --env-file .env.prod up -d --remove-orphans
          host: domiz.org
          port: 22
          username: root
          key: ${{ secrets.DMZ_GIT_ACTIONS_PROD }}
