name: P2P ifrastructure to DEV

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    environment:
      name: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Copy files on server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.MAIN_DOMAIN }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.DEV_SERVER_KEY }}
          source: docker,docker-compose-dev-01.yaml
          target: /srv/p2p-infrastructure
          overwrite: true
          debug: true

      - name: Docker compose up
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd /srv/p2p-infrastructure
            touch .htpasswd
            htpasswd -bB .htpasswd ${{ vars.BASIC_AUTH_USER }} ${{ secrets.BASIC_AUTH_PASSWORD }}
            export EMAIL=${{ vars.EMAIL }}
            export TRAEFIK_DOMAIN=${{ vars.TRAEFIK_DOMAIN }}
            export METRICS_DOMAIN=${{ vars.METRICS_DOMAIN }}
            export WHOAMI_DOMAIN=${{ vars.WHOAMI_DOMAIN }}
            export NODE_DOMAIN=${{ vars.NODE_DOMAIN }}
            export PROMETHEUS_DOMAIN=${{ vars.PROMETHEUS_DOMAIN }}
            docker compose -f docker-compose-dev-01.yaml pull
            docker compose -f docker-compose-dev-01.yaml down --verbose
            docker compose -f docker-compose-dev-01.yaml up -d --remove-orphans
          host: ${{ vars.MAIN_DOMAIN }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.DEV_SERVER_KEY }}
